batch_size:      2                                      # Numbers of videos in a mini-batch 
clip_length:     16                                     # Number of frames within a clip 
clip_offset:     0                                      # Frame offset between beginning of video and clip (1st clip only) 
clip_stride:     0                                      # Frame offset between successive frames
crop_shape:      [224,224]                              # (Height, Width) of frame  
crop_type:       Random                                 # Type of cropping operation (Random, Central and None)  
dataset:         MSCOCO                                 # Name of dataset 
epoch:           10                                     # Total number of epochs 
exp:             exp                                    # Experiment name
final_shape:     [224,224]                              # (Height, Width) of input to be given to CNN
gamma:           0.2                                    # Multiplier with which to change learning rate
json_path:       /z/home/erichof/datasets/mscoco/       # Path to the json file for the given dataset
labels:          80                                     # Number of total classes in the dataset
load_type:       train                                  # Environment selection, to include only training/training and validation/testing dataset
loss_type:       HGC_MSE                                # Loss class to be loaded
lr:              0.001                                  # Learning rate
milestones:      [100, 150, 200]                        # Epoch values to change learning rate     
model:           HGC3D                                  # Name of model to be loaded  
momentum:        0.9                                    # Momentum value in optimizer
num_clips:       -1                                     # Number clips to be generated from a video (<0: uniform sampling, 0: Divide entire video into clips, >0: Defines number of clips) 
opt:             sgd                                    # Name of optimizer
rerun:           5                                      # Number of trials to repeat an experiment
resize_shape:    [256,256]                              # (Height, Width) to resize original data 
sample_duration: 16                                     # Temporal size of video to be provided as input to the model 
sample_size:     224                                    # Height of frame to be provided as input to the model
save_dir:        './results'                            # Path to results directory
seed:            998                                    # Seed for reproducibility  
subtract_mean:   ''                                     # Subtract mean (R,G,B) from all frames during preprocessing
weight_decay:    0.0005                                 # Weight decay
